spring.application.name=blog

spring.datasource.url=jdbc:h2:mem:blog
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true

spring.jackson.property-naming-strategy=SNAKE_CASE

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json
springdoc.packages-to-scan=com.example.blog
springdoc.swagger-ui.default-models-expand-depth=2
springdoc.swagger-ui.default-model-expand-depth=2

jwt.secret=${JWT_SECRET:LeetsBackendKx5!93Jv#1Rz@lQwT9pXe3bD7sUaFzYt}
jwt.access-expiration=1800000
jwt.refresh-expiration=1209600000
jwt.cookie.secure=false
