spring:
  application:
    name: leets-7th

  datasource:
    url: ${DB_URL}
    username: ${LOCAL_DB_NAME}
    password: ${LOCAL_DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs