spring:
  application:
    name: blog
  profiles:
    active: prod

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/blog}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:hhr120810}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

# swagger 설정
springdoc:
  swagger-ui:
    path: /docs # Swagger 경로
    enabled: ${SWAGGER_ENABLE:true} # Swagger는 기본적으로 비활성화

    # 정렬 옵션
    groups-order: DESC  # 그룹 정렬 (ASC/DESC)
    tags-sorter: alpha  # 태그(컨트롤러) 정렬
    operations-sorter: method  # API 메소드 정렬

    # UI 설정
    doc-expansion: none  # API 펼침 상태 (none/list/full)
    disable-swagger-default-url: true  # petstore 기본 URL 비활성화
    display-request-duration: true  # 요청 소요 시간 표시
    display-operation-id: false  # operation ID 표시 여부

    filter: true
    #    default-models-expand-depth: -1  # 스키마 모델도 접힌 상태로

    # 기타
    deep-linking: true  # URL 딥링킹 지원
    show-extensions: true  # 확장 속성 표시
    show-common-extensions: true  # 공통 확장 속성 표시

logging:
  level:
    root: info
    com.umc.product: debug   # 코드 로그 더 자세히 보기
    org.hibernate.SQL: debug   # 실행되는 SQL 로그
    org.hibernate.type.descriptor.sql: trace   # 파라미터 값까지 출력

app:
  oauth:
    kakao:
      client-id: ${KAKAO_CLIENT_ID:locat_test_id}
      client-secret: ${KAKAO_CLIENT_SECRET:local_test_secret}
      redirect-uri: ${KAKAO_REDIRECT_URL:http://localhost:8080/login/oauth2/code/kakao}
      connect-timeout-millis: 3000
      read-timeout-millis: 5000


jwt:
  access-token-secret: "local-access-token-secret-key-for-blog-project-2026"
  refresh-token-secret: "local-refresh-token-secret-key-for-blog-project-2026"
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 1209600

