spring.application.name=assignment

# H2 데이터베이스 설정
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 콘솔 설정 (웹 브라우저에서 DB 확인 가능)
spring.h2.console.enabled=true

# JPA/Hibernate 설정
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# data.sql 초기화 모드 설정 (data.sql 등을 항상 실행)
spring.sql.init.mode=always

# Hibernate의 테이블 생성(ddl-auto)이 완료된 후 data.sql이 실행되도록 설정
spring.jpa.defer-datasource-initialization=true