services:
  mysql:
    image: mysql:8.4
    container_name: my-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: leets_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 20s
      retries: 10

  app:
    image: ${DOCKER_IMAGE:-week2-app:latest}

    container_name: spring-app

    ports:
      - "8081:8080"

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/leets_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_CONFIG_ADDITIONAL_LOCATION: optional:file:/app/application.yml

    volumes:
      - ./application.yml:/app/application.yml:ro

volumes:
  mysql-data:
